---
sudo: false
language: python
matrix:
  # Checks
  - env: TOXENV=flake8
  - env: TOXENV=mypy
  - env: TOXENV=bandit
  - env: TOXENV=xenon
  - env: TOXENV=yamllint

  # Tests
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.8
    env: TOXENV=py38

install:
  - pip install tox==3.15.1
script:
  - tox
